" Vim configuration by Giako
" Inspired from https://dougblack.io/words/a-good-vimrc.html

" Colors
syntax enable " enable syntax processing
colorscheme badwolf " set colorscheme
set termguicolors

" Spaces and tabs
set tabstop=4 " number of visual spaces per TAB
set softtabstop=4 " number of spaces in tab when editing
set expandtab " tabs are spaces
set shiftwidth=4
filetype indent on
filetype plugin on
set autoindent

" UI config
set number " show line numbers
set wildmenu " visual autocomplete for command menu
